### ISSUE TITLE
LTS-8.0 compatibility

### ISSUE THREAD

**Issue by ejconlon** [JustusAdam/marvin#6]
marvin does not build on the recently released [lts-8.0 package set](https://www.stackage.org/lts-8.0). Perhaps relaxing version bounds would fix things.

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for marvin-0.1.4:
    directory-1.3.0.0 must match ==1.2.* (latest applicable is 1.2.7.1)
    websockets-0.10.0.0 must match ==0.9.* (latest applicable is 0.9.8.2)
```

**Comment by JustusAdam** [comment]
I don't really understand how that can be. As far as I remember the version bounds were not that strict. I'm investigating.

**Comment by JustusAdam** [comment]
Oh no ... I forgot to remove `pvp-bounds` from my stack.yaml before uploading 🙈

**Comment by JustusAdam** [comment]
I think I fixed it.

**Comment by ejconlon** [comment]
Thanks for taking a look! I will post back when I'm able to test it out.

**Comment by ejconlon** [comment]
Just confirmed this works on lts-8.1 . Thank you!
